// "use client"
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import CarContext from "@/context/CarContext";
import Loading from "./(public)/loading";

import "../globals.css";
import IdContext from "@/context/IdContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portofino",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <IdContext>
            <CarContext>
              {/* {isLoading ? <Loading /> : null} */}
              {children}
            </CarContext>
          </IdContext>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
